#!/bin/bash

# Investment Platform - Railway Deployment Setup Script
# This script helps prepare the platform for deployment to Railway

set -e

echo "=========================================="
echo "Investment Platform - Railway Deployment"
echo "=========================================="
echo ""

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v git &> /dev/null; then
    echo "❌ Git is required but not installed."
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is required but not installed."
    exit 1
fi

echo "✓ Git and Python 3 are installed"
echo ""

# Generate JWT Secret Key
echo "Step 1: Generating JWT Secret Key"
echo "=================================="
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo "Generated SECRET_KEY: $SECRET_KEY"
echo ""
echo "⚠️  IMPORTANT: Save this key somewhere safe!"
echo "You'll need to set this as an environment variable in Railway."
echo ""

# Get API Keys
echo "Step 2: External API Keys"
echo "========================="
echo ""
echo "You'll need API keys from these services:"
echo "  1. Alpha Vantage: https://www.alphavantage.co/"
echo "  2. MarketAux: https://www.marketaux.com/"
echo "  3. NewsAPI: https://newsapi.org/"
echo "  4. Finnhub: https://finnhub.io/"
echo ""
read -p "Have you obtained all API keys? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please obtain API keys first, then re-run this script."
    exit 1
fi

echo ""
echo "Step 3: Allowlist Configuration"
echo "================================"
read -p "Enter comma-separated emails to auto-approve (e.g., admin@example.com,user@example.com): " allowlist_emails

if [ -z "$allowlist_emails" ]; then
    allowlist_emails="admin@example.com"
    echo "Using default: $allowlist_emails"
fi

echo ""
echo "Step 4: Custom Domain (Optional)"
echo "================================="
read -p "Do you want to use a custom domain? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter your custom domain (e.g., api.example.com): " custom_domain
else
    custom_domain=""
fi

echo ""
echo "=========================================="
echo "Deployment Configuration Summary"
echo "=========================================="
echo ""
echo "Frontend URL: Auto-generated by Railway"
echo "API Gateway URL: Auto-generated by Railway"
echo "Custom Domain: ${custom_domain:-None}"
echo "Allowlist Emails: $allowlist_emails"
echo ""

# Create deployment guide
echo "Step 5: Creating Deployment Guide"
echo "=================================="

cat > /tmp/railway_setup_guide.txt << EOF
Investment Platform - Railway Deployment Variables

=== Gateway Service (gateway-service) ===
ENVIRONMENT=production
DEBUG=False
LOG_LEVEL=INFO
SECRET_KEY=$SECRET_KEY
JWT_ALGORITHM=HS256
JWT_EXPIRATION_HOURS=24
ALLOWLIST_EMAILS=$allowlist_emails
SERVICE_NAME=gateway-service
SERVICE_PORT=8000
MARKET_DATA_BASE_URL=http://market-data-service:8001
NEWS_SERVICE_BASE_URL=http://news-service:8002
ML_SIGNAL_BASE_URL=http://ml-signal-service:8003
REQUEST_TIMEOUT_SECONDS=30

=== Market Data Service (market-data-service) ===
ENVIRONMENT=production
DEBUG=False
LOG_LEVEL=INFO
ALPHA_VANTAGE_API_KEY=<your_alpha_vantage_key_here>
SERVICE_NAME=market-data-service
SERVICE_PORT=8001
REQUEST_TIMEOUT_SECONDS=30

=== News Service (news-service) ===
ENVIRONMENT=production
DEBUG=False
LOG_LEVEL=INFO
MARKETAUX_API_TOKEN=<your_marketaux_key_here>
SERVICE_NAME=news-service
SERVICE_PORT=8002
REQUEST_TIMEOUT_SECONDS=30

=== ML Signal Service (ml-signal-service) ===
ENVIRONMENT=production
DEBUG=False
LOG_LEVEL=INFO
SERVICE_NAME=ml-signal-service
SERVICE_PORT=8003
REQUEST_TIMEOUT_SECONDS=30

=== Frontend Service (frontend-service) ===
ENVIRONMENT=production
DEBUG=False
REACT_APP_BACKEND_URL=<will_be_set_after_gateway_deployment>

=== PostgreSQL (Auto-managed by Railway) ===
Database: investment_platform
User: investment_user
Password: <generated_by_railway>

=== Redis (Auto-managed by Railway) ===
URL: <generated_by_railway>

CUSTOM DOMAIN SETUP (if needed):
If you want to use: $custom_domain
1. Add custom domain in Railway dashboard
2. Update your DNS CNAME record to point to Railway's provided endpoint
3. Wait for DNS propagation (5-30 minutes)
EOF

cat /tmp/railway_setup_guide.txt

echo ""
echo "✓ Configuration guide saved to: /tmp/railway_setup_guide.txt"
echo ""

# Git verification
echo "Step 6: Git Repository Check"
echo "============================="

if [ -d .git ]; then
    echo "✓ Git repository found"

    # Check if there are uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        echo "⚠️  Warning: You have uncommitted changes"
        echo "Please commit all changes before deploying to Railway"
        read -p "Continue anyway? (y/n) " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi

    # Check GitHub remote
    if git remote get-url origin &> /dev/null; then
        echo "✓ GitHub remote configured"
        echo "Remote: $(git remote get-url origin)"
    else
        echo "⚠️  No GitHub remote found"
        echo "You need to push to GitHub for Railway deployment"
    fi
else
    echo "⚠️  Git repository not found"
    echo "Railway will still deploy but may have issues with git-based builds"
fi

echo ""
echo "=========================================="
echo "Next Steps:"
echo "=========================================="
echo ""
echo "1. Go to https://railway.app and create a new project"
echo "2. Connect your GitHub repository"
echo "3. Railway will automatically detect and deploy:"
echo "   - PostgreSQL database"
echo "   - Redis cache"
echo "   - All microservices"
echo "   - Frontend"
echo ""
echo "4. Add environment variables in Railway dashboard:"
echo "   - Copy variables from: /tmp/railway_setup_guide.txt"
echo "   - Set each service's variables in the Variables section"
echo ""
echo "5. Configure domains:"
echo "   - Generate public domains for gateway and frontend"
echo "   - Update REACT_APP_BACKEND_URL in frontend service"
echo ""
echo "6. Test deployment:"
echo "   - Open frontend URL in browser"
echo "   - Try registering with allowlisted email"
echo "   - Verify API keys can be configured"
echo "   - Test dashboard with real data"
echo ""
echo "7. (Optional) Set up custom domain"
echo ""

echo "For detailed instructions, see: DEPLOYMENT.md"
echo ""
echo "=========================================="
echo "✓ Setup script completed!"
echo "=========================================="
